### ISSUE TITLE
No accept header drops the entire request detail

### ISSUE THREAD

**Issue by CmdrDats** [ring-clojure/ring-accept#2]
https://github.com/ring-clojure/ring-accept/blob/e478fac6da8d330972029e8c33809b8dc0fdd39c/src/ring/middleware/accept.clj#L37

There's no else case, you probably want to return `request` unchanged here.

**Comment by weavejester** [comment]
This library is unfinished and unreleased. I'd advise looking at more mature solutions like [Muuntaja](https://github.com/metosin/muuntaja).

**Comment by CmdrDats** [comment]
Hi, yes - I was aware that the library is unfinished (the 0.1.0-SNAPSHOT), but I just thought I'd help share the issue I found when using it is all. I am looking to switch to Muuntaja at some point, but I needed a  lighter solution in the meantime.
